apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 79951d719642/backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: postgres
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_USER
              value: user
            - name: DATABASE_PASSWORD
              value: password
            - name: DATABASE_NAME
              value: imageapp