apiVersion: v1
kind: Service
metadata:
  name: image-app-frontend
  labels:
    app: image-app-frontend
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80