apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc      # deve bater com claimName do Deployment
  namespace: dev          # importante
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi