apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-hml
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/orbite82/k8s-argo-cd.git'
    targetRevision: main
    path: python-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/orbite82/k8s-argo-cd.git'
    targetRevision: prod
    path: python-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/orbite82/k8s-argo-cd.git'
    targetRevision: prod   # <<<<< branch PROD
    path: python-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true