apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/orbite82/k8s-argo-cd.git
    targetRevision: main
    path: apps/image-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true          # aplica apenas recursos fora de sincronia
      - Validate=false                   # evita falha de validação se algo estiver temporariamente ausente